import type { Column, RelationEdge, TableNode } from "@/lib/types";
import { quoteIdent } from "@/lib/codegen/naming";
import {
  columnDbName,
  colIndex,
  joinTableName,
  resolveJoinTableSides,
  resolveRelations,
  tableDbName,
  type ResolvedRelation,
} from "@/lib/codegen/resolve-schema";
import { sqlDefault, sqlType } from "@/lib/codegen/type-maps";

function renderColumnDef(column: Column, index: number): string {
  const name = quoteIdent(columnDbName(column, index));
  const type = sqlType(column);
  const notNull = !column.isNullable ? " NOT NULL" : "";
  // A PRIMARY KEY constraint already implies uniqueness — skip the redundant UNIQUE.
  const unique = column.isUnique && !column.isPrimaryKey ? " UNIQUE" : "";
  const def = sqlDefault(column);
  const defaultClause = def ? ` DEFAULT ${def}` : "";
  return `  ${name} ${type}${notNull}${unique}${defaultClause}`;
}

function renderCreateTable(table: TableNode, index: number): string[] {
  const name = quoteIdent(tableDbName(table, index));
  const columnLines = table.data.columns.map((c, i) => renderColumnDef(c, i));

  const pkColumns = table.data.columns.filter((c) => c.isPrimaryKey);
  if (pkColumns.length > 0) {
    const pkNames = pkColumns
      .map((c) => quoteIdent(columnDbName(c, colIndex(table, c))))
      .join(", ");
    columnLines.push(`  PRIMARY KEY (${pkNames})`);
  }

  if (columnLines.length === 0) {
    return [`CREATE TABLE ${name} (`, `  -- no columns defined`, `);`];
  }

  return [`CREATE TABLE ${name} (`, columnLines.join(",\n"), `);`];
}

function renderJoinTable(rel: ResolvedRelation): string[] {
  const sides = resolveJoinTableSides(rel);
  if (!sides) {
    const childName = tableDbName(rel.childTable, rel.childTableIndex);
    const parentName = tableDbName(rel.parentTable, rel.parentTableIndex);
    return [`-- Skipped many-to-many join table for "${childName}" <-> "${parentName}": a table has no columns.`];
  }
  const { first, second, joinTableName: joinName } = sides;

  return [
    `CREATE TABLE ${quoteIdent(joinName)} (`,
    `  ${quoteIdent(first.columnName)} ${sqlType(first.pkColumn)} NOT NULL REFERENCES ${quoteIdent(
      first.tableName
    )} (${quoteIdent(columnDbName(first.pkColumn, colIndex(first.table, first.pkColumn)))}),`,
    `  ${quoteIdent(second.columnName)} ${sqlType(second.pkColumn)} NOT NULL REFERENCES ${quoteIdent(
      second.tableName
    )} (${quoteIdent(columnDbName(second.pkColumn, colIndex(second.table, second.pkColumn)))}),`,
    `  PRIMARY KEY (${quoteIdent(first.columnName)}, ${quoteIdent(second.columnName)})`,
    `);`,
  ];
}

function renderForeignKey(rel: ResolvedRelation): string {
  const childTableName = tableDbName(rel.childTable, rel.childTableIndex);
  const childColName = columnDbName(rel.childColumn, colIndex(rel.childTable, rel.childColumn));
  const parentTableName = tableDbName(rel.parentTable, rel.parentTableIndex);
  const parentColName = columnDbName(rel.parentColumn, colIndex(rel.parentTable, rel.parentColumn));
  const constraintName = `fk_${childTableName}_${childColName}`;

  return `ALTER TABLE ${quoteIdent(childTableName)} ADD CONSTRAINT ${quoteIdent(
    constraintName
  )} FOREIGN KEY (${quoteIdent(childColName)}) REFERENCES ${quoteIdent(parentTableName)} (${quoteIdent(
    parentColName
  )});`;
}

/** For 1-to-1 relations, the FK column also needs a UNIQUE constraint (skipped if it already has one). */
function renderUniqueForOneToOne(rel: ResolvedRelation): string | undefined {
  if (rel.childColumn.isUnique || rel.childColumn.isPrimaryKey) return undefined;
  const childTableName = tableDbName(rel.childTable, rel.childTableIndex);
  const childColName = columnDbName(rel.childColumn, colIndex(rel.childTable, rel.childColumn));
  const constraintName = `uq_${childTableName}_${childColName}`;
  return `ALTER TABLE ${quoteIdent(childTableName)} ADD CONSTRAINT ${quoteIdent(
    constraintName
  )} UNIQUE (${quoteIdent(childColName)});`;
}

export function generateSQL(nodes: TableNode[], edges: RelationEdge[]): string {
  const lines: string[] = [
    "-- Generated by BluePrintDB",
    "-- Dialect: PostgreSQL",
    "",
  ];

  nodes.forEach((table, index) => {
    lines.push(...renderCreateTable(table, index), "");
  });

  const relations = resolveRelations(nodes, edges);
  const manyToMany = relations.filter((r) => r.relationType === "many-to-many");
  const direct = relations.filter((r) => r.relationType !== "many-to-many");

  const seenJoinTables = new Set<string>();
  for (const rel of manyToMany) {
    const name = joinTableName(
      tableDbName(rel.childTable, rel.childTableIndex),
      tableDbName(rel.parentTable, rel.parentTableIndex)
    );
    if (seenJoinTables.has(name)) continue;
    seenJoinTables.add(name);
    lines.push(...renderJoinTable(rel), "");
  }

  if (direct.length > 0) {
    lines.push("-- Foreign key constraints");
    for (const rel of direct) {
      lines.push(renderForeignKey(rel));
      const uniqueClause =
        rel.relationType === "one-to-one" ? renderUniqueForOneToOne(rel) : undefined;
      if (uniqueClause) lines.push(uniqueClause);
    }
  }

  if (nodes.length === 0) {
    lines.push("-- Add a table on the canvas to generate its CREATE TABLE statement.");
  }

  return lines.join("\n").trimEnd() + "\n";
}
